pipeline {
    agent any

    stages {
        stage('Test in Docker') {
            steps {
                script {
                    docker.image('node:16-alpine').inside {
                        sh 'node --version'
                    }
                }
            }
        }
    }
}
